### ISSUE TITLE
Issue with searching for lyrics

### ISSUE THREAD

**Issue by Mar0xy** [J0R6IT0/lyricsfinder#1]
I have noticed that for some reason I have to call the findLyrics function multiple times to get lyrics and I don't know how this issue comes around. In the picture below I ran the command three times to finally get the lyrics
![image](https://user-images.githubusercontent.com/8841466/132065935-607d7887-aaa2-4a78-8c83-f268b1827578.png)

**Comment by Mar0xy** [comment]
Here is another example
![image](https://user-images.githubusercontent.com/8841466/132066173-96d5c25f-f262-4d8c-bc22-cd20fe6947ce.png)

**Comment by J0R6IT0** [comment]
Hey, thanks for reporting! Does it happen with every song?

**Comment by J0R6IT0** [comment]
ouch, working fine on my end x.x. I'll try to find what's going on.

**Comment by J0R6IT0** [comment]
Published a new update. Try it and lemme know if it works better. Genius sometimes doesn't return a proper html with lyrics, even when using the same url, so the module falls back to Google. But apparently sometimes the Google scraper doesn't work for about 0.5-1h. Not sure why, maybe updates going on in Google. 

Now it will try several times to get the lyrics from Genius (if song is found).

**Comment by Mar0xy** [comment]
Yep that fixed the issue I was having 👍

**Comment by J0R6IT0** [comment]
Cool! Lemme know if you find any other bug. 🙂
