### ISSUE TITLE
Invalid JSON response

### ISSUE THREAD

**Issue by JeremyBorja** [J0R6IT0/lyricsfinder#2]
Hi, i was using your package and is awesome, but now i have this error when i try to find a song lyrics, it happens with every song i search.

![image](https://user-images.githubusercontent.com/79943501/132140463-46b73118-d83c-44fd-ba08-d21e32ade603.png)

Package version: 1.1.1
Thanks for doing a great package for lyrics.

**Comment by J0R6IT0** [comment]
Hey, thanks for reporting! Unfortunately I cannot reproduce this. Did it work fine in previous versions?

**Comment by JeremyBorja** [comment]
I tried to see if it works with previous versions and sadly it didn't work.
It happens the same thing
